sudo: required
dist: xenial

services:
  - docker

git:
  depth: 5

jobs:
  include:
    - stage: build prometsource/base image
      script:
      - docker build -t base ./docker/base/.
      - docker run -it --rm base bash -c 'cat /etc/os-release' > "release"
      - source release
      - ver1=${PRETTY_NAME// LTS}
      - ver1=${ver1// /-}
      - ver1=${ver1,,}
      - ver1=${ver1/$'\r'/}
      - ver2=${VERSION_ID/$'\r'/}
      - docker tag base prometsource/base
      - docker tag base prometsource/base:$ver1
      - docker tag base prometsource/base:ubuntu-$ver2
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker push prometsource/base
      - docker push prometsource/base:$ver1
      - docker push prometsource/base:ubuntu-$ver2
    - stage: build prometsource/apache2 image
      script:
      - docker build -t apache2 ./docker/apache2/.
      - docker run -d --name apache2 apache2
      - docker exec apache2 bash -c 'cat /etc/os-release' > "release"
      - source release
      - ver1=${PRETTY_NAME// LTS}
      - ver1=${ver1// /-}
      - ver1=${ver1,,}
      - ver1=${ver1/$'\r'/}
      - ver2=${VERSION_ID/$'\r'/}
      - docker tag apache2 prometsource/apache2
      - docker tag apache2 prometsource/apache2:$ver1
      - docker tag apache2 prometsource/apache2:ubuntu-$ver2
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker push prometsource/apache2
      - docker push prometsource/apache2:$ver1
      - docker push prometsource/apache2:ubuntu-$ver2
    - stage: build prometsource/php base image
      script:
      - cp ./docker/php/Dockerfile-php ./docker/php/Dockerfile
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t php ./docker/php/.
      - docker run -it --rm php bash -c 'cat /etc/os-release' > "release"
      - source release
      - ver1=${PRETTY_NAME// LTS}
      - ver1=${ver1// /-}
      - ver1=$(echo "$ver1" | awk '{print tolower($0)}')
      - ver1=${ver1/$'\r'/}
      - ver2=${VERSION_ID/$'\r'/}
      - docker tag php prometsource/php
      - docker tag php prometsource/php:$ver1
      - docker tag php prometsource/php:ubuntu-$ver2
      - docker push prometsource/php
      - docker push prometsource/php:$ver1
      - docker push prometsource/php:ubuntu-$ver2
    - stage: build prometsource/php7.3 image
      script:
      - cp ./docker/php/Dockerfile-php7.3 ./docker/php/Dockerfile
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t php7.3 ./docker/php/.
      - docker run -it --rm php7.3 bash -c 'php -v'
      - docker run -it --rm php7.3 bash -c 'cat /etc/os-release' > "release"
      - source release
      - ver1=${PRETTY_NAME// LTS}
      - ver1=${ver1// /-}
      - ver1=$(echo "$ver1" | awk '{print tolower($0)}')
      - ver1=${ver1/$'\r'/}
      - ver2=${VERSION_ID/$'\r'/}
      - docker tag php7.3 prometsource/php7.3
      - docker tag php7.3 prometsource/php7.3:$ver1
      - docker tag php7.3 prometsource/php7.3:ubuntu-$ver2
      - docker push prometsource/php7.3
      - docker push prometsource/php7.3:$ver1
      - docker push prometsource/php7.3:ubuntu-$ver2      
    - stage: build prometsource/php7.2 image
      script:
      - cp ./docker/php/Dockerfile-php7.2 ./docker/php/Dockerfile
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t php7.2 ./docker/php/.
      - docker run -it --rm php7.2 bash -c 'php -v'
      - docker run -it --rm php7.2 bash -c 'cat /etc/os-release' > "release"
      - source release
      - ver1=${PRETTY_NAME// LTS}
      - ver1=${ver1// /-}
      - ver1=$(echo "$ver1" | awk '{print tolower($0)}')
      - ver1=${ver1/$'\r'/}
      - ver2=${VERSION_ID/$'\r'/}
      - docker tag php7.2 prometsource/php7.2
      - docker tag php7.2 prometsource/php7.2:$ver1
      - docker tag php7.2 prometsource/php7.2:ubuntu-$ver2
      - docker push prometsource/php7.2
      - docker push prometsource/php7.2:$ver1
      - docker push prometsource/php7.2:ubuntu-$ver2      
    - stage: build prometsource/php7.1 image
      script:
      - cp ./docker/php/Dockerfile-php7.1 ./docker/php/Dockerfile
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t php7.1 ./docker/php/.
      - docker run -it --rm php7.1 bash -c 'php -v'
      - docker run -it --rm php7.1 bash -c 'cat /etc/os-release' > "release"
      - source release
      - ver1=${PRETTY_NAME// LTS}
      - ver1=${ver1// /-}
      - ver1=$(echo "$ver1" | awk '{print tolower($0)}')
      - ver1=${ver1/$'\r'/}
      - ver2=${VERSION_ID/$'\r'/}
      - docker tag php7.1 prometsource/php7.1
      - docker tag php7.1 prometsource/php7.1:$ver1
      - docker tag php7.1 prometsource/php7.1:ubuntu-$ver2
      - docker push prometsource/php7.1
      - docker push prometsource/php7.1:$ver1
      - docker push prometsource/php7.1:ubuntu-$ver2
    - stage: build prometsource/php7.1:drupal-light-apache image
      script:
      - cp ./docker/php/Dockerfile-php7.1-drupal-light-apache ./docker/php/Dockerfile
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t php7.1:drupal-light-apache ./docker/php/.
      - docker run -it --rm php7.1:drupal-light-apache php -v
      - docker tag php7.1:drupal-light-apache prometsource/php7.1:drupal-light-apache
      - docker push prometsource/php7.1:drupal-light-apache
